# this is our development docker-compose building on top of the prodicker docker-compose, just mounting
# the sync image - not redefining anything else

version: "2"
services:
  app-simplest:
    volumes:
      - simplest-sync:/var/www/html:nocopy # will be mounted on /var/www

# that the important thing
volumes:
  simplest-sync:
    external: true
